version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HueLogging:MachineHostIp}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    environment:
      CASSANDRA_BROADCAST_ADDRESS: ${HueLogging:MachineHostIp}
    volumes:
      - ${HueLogging:CassandraVolumePath}:/var/lib/cassandra
  polling-service:
    build:
      context: ./main/src
      dockerfile: HueLogging.ServiceV2/.Dockerfile
    environment:
        HueLogging:Kafka:BootstrapServers: "kafka:9092"
    links:
      - "kafka"
    env_file:
      - .env
    depends_on:
      - kafka
  jobmanager:
    image: flink
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    links:
      - "cassandra:cassandra"
      - "kafka:kafka"
  taskmanager:
    image: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
      - "cassandra:cassandra"
      - "kafka:kafka"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

